protyagov/martspec

- src/part/navbar.tsx
- made links clickable
- added Private Policy link to navbar as we have it in footer
> [MS-163] Navbar links' hrefs update

- src/i18n/es.json
> [MS-1065] ES: Translate ENERGY page: spelling mistakes

- src/i18n/es.json
> [MS-1023] ES: Translate productivity page: spelling mistakes

- src/template/de/emotion/energy.ejs
> [MS-977] Translate title and description page energy_Update energy.ejs

- src/sass/page/emotion/personality-trait.scss
Мне сказали, что это все еще не работает в Chrome. Переделал.
> [MS-1038] new update

- src/i18n/es.json
> ES Emotion page_Update es.json

- src/atomic/page/emotion/biorhythms.tsx
I changed alt attribute for main image
Buttons don`t contain the alt attribute
> MS-1178-Biorhythms

- src/i18n/es.json
> [MS-1186] ES: Translate Careers page_Update es.json

- src/i18n/es.json
> [MS-1163] ES Body mass page_Update es.json

- .gitignore
- .vscode/settings.json
- src/atomic/organism/navbar.tsx
- src/sass/organism/navigation.scss
> Header: change how menus are displayed

- src/atomic/page/bodyzinc.tsx
> MS-1220-App-Store

- src/template/en/emotion.ejs
> MS-1157-Change-Canonical

- src/sass/molecule/page-header.scss
- src/sass/page/base.scss
jun19: font-size + word-break, багфикс
jun25: git fetch/pull, загрузил последние изменения репозитория
> Ms 1136 heading word break

- .gitignore
- .vscode/settings.json
- src/template/en/about.ejs
- src/template/en/team.ejs
changed og:description for about and team pages
> [MS-535] change meta descriptions for en pages

- src/atomic/molecule/card-title-subtitle.tsx
- src/atomic/molecule/page-header.tsx
- src/atomic/organism/call-to-action.tsx
- src/atomic/organism/header.tsx
- src/atomic/organism/navbar.tsx
- src/atomic/page/emotion/color-test.tsx
- src/atomic/prototype/vacancy-details.tsx
- src/atomic/prototype/vitamin-element.tsx
- src/event-bus.ts
- src/hooks.tsx
- src/index.tsx
- tsconfig.json
Для qa, видимо, нужно будет составить список страниц на проверку, так как исправления касаются многих страниц.
исправления:
- в основном базовая проверка/выброс ошибки.
- местами подправлены сами типы
- где-то чуть подальнее, добавление нового метода/изменение принимаемых параметров у функции.
сами компоненты я не изменял, придерживался уже написанной структуры.
> Ms 1261 strict null checks

- src/sass/main.scss
- src/sass/page/base.scss
- src/sass/page/careers.scss
- src/sass/page/electrolyte.scss
- src/sass/prototype/vacancy-details.scss
It's a bit confusing that there is repeating code in two scss files, maybe it's wrong
> MS-1265-Correcting-Word-Hyphenation

- src/hooks/useReviewData.ts
if link is broken -> validate runs with empty arr -> validate returns arr with fillers -> set fillers
> [MS-1301] add error catching logic

- src/template/ar/emotion.ejs
- src/template/de/emotion.ejs
- src/template/en/emotion.ejs
- src/template/es/emotion.ejs
- src/template/fr/emotion.ejs
- src/template/hi/emotion.ejs
- src/template/ja/emotion.ejs
- src/template/pt/emotion.ejs
- src/template/ru/emotion.ejs
- src/template/uk/emotion.ejs
- src/template/zh/emotion.ejs
changed templates for Emotion Page
> [MS-1275] added json-lds for emotion templates

- package.json
docs:
- https://nodejs.org/api/packages.html#packagemanager 
- https://github.com/nodejs/corepack?tab=readme-ov-file#when-authoring-packages
> [MS-1306] add package manager field

- README.md
rewrite ladle description text
> readme: update ladle description text

- src/stories/atom/button-apple.stories.tsx
Добавлена Ladle story по компоненту ButtonApple (уровень - атом).
> [MS-1313] Ladle-ButtonApple-Story

- .gitignore
Установлена новая версия Yarn (использовалась команда yarn set version stable). В файле gitignore добавлены правила относительно Yarn (настройки взяты с официального сайта: https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored).
> [MS-1314] feat: change yarn version to latest stable version, add gitignore rules

- src/stories/atom/star-icon.stories.tsx
Добавлена Ladle story по компоненту StarIcon (уровень - атом).
> [MS-1317] Ladle: add StarIcon story

- src/stories/atom/icon-chevron-circle.stories.tsx
Добавлена Ladle story для компонента IconChevronCircle, уровень - Атом.
> [MS-1320] Ladle: add IconChevronCircle story

- src/stories/molecule/accordion.stories.tsx
Добавлена story по компоненту Accordion (уровень - молекула). В качестве вложения (пропс children) использована надпись-"заглушка" (для изолированного представления компонента).
> [MS-1322] Ladle: add Accordion story

- src/stories/molecule/card-vitamin.stories.tsx
Добавлена Ladle story для компонента CardVitamin, уровень - Молекула.
> [MS-1330] Ladle: add CardVitamin story

- src/stories/molecule/team-member.stories.tsx
В Ladle добавлена story для компонента TeamMember (уровень "молекула")
> [MS-1338] Ladle: add TeamMember story 

- src/stories/molecule/title-text-link-card.stories.tsx
Добавлена Ladle story для компонента TitleTextLinkCard , уровень - Молекула.
> [MS-1342] Ladle: add TitleTextLinkCard story

- src/stories/organism/navbar.stories.tsx
Добавлена Navigation Bar story в Ladle (уровень "организм").
> [MS-1354] Ladle: add NavigationBar story 

- src/stories/organism/icon-title-text-list.stories.tsx
Добавлена story для компонента IconTitleTextList в Ladle (уровень "Организм").
> [MS-1353] Ladle: add IconTitleTextList story

- src/stories/organism/header.stories.tsx
Добавлена в Ladle история для Header (уровень - организм).
> [MS-1351] Ladle: add Header story 

- src/stories/organism/call-to-action.stories.tsx
Добавлена в Ladle story компонента CallToAction (уровень "организм").
> [MS-1346] Ladle: add CallToAction story

- src/stories/molecule/text-link-arrow.stories.tsx
Добавлена Ladle story для компонента TextLinkArrow, уровень - Молекула.
> [MS-1343] Ladle: add TextLinkArrow story

- src/stories/organism/footer.stories.tsx
Добавлена Ladle story для компонента Footer (уровень — Организм).
> [MS-1347] Ladle: add Footer story

- src/stories/organism/review-link.stories.tsx
Добавлена Ladle story для компонента ReviewLink (уровень — Организм).
> [MS-1370] Ladle: add ReviewLink story

- src/atomic/atom/scroll-button.tsx
- src/atomic/page/about.tsx
- src/atomic/page/bodysize.tsx
- src/atomic/page/bodyzinc.tsx
- src/atomic/page/careers.tsx
- src/atomic/page/electrolyte.tsx
- src/atomic/page/emotion.tsx
- src/atomic/page/emotion/anxiety.tsx
- src/atomic/page/emotion/biorhythms.tsx
- src/atomic/page/emotion/color-test.tsx
- src/atomic/page/emotion/energy.tsx
- src/atomic/page/emotion/harmony.tsx
- src/atomic/page/emotion/independence.tsx
- src/atomic/page/emotion/openness.tsx
- src/atomic/page/emotion/productivity.tsx
- src/atomic/page/main.tsx
- src/atomic/page/mass.tsx
- src/atomic/page/mission.tsx
- src/atomic/page/private-policy.tsx
- src/atomic/page/team.tsx
- src/atomic/page/vitamin.tsx
- src/atomic/page/waist.tsx
- src/sass/atom/scroll-button.scss
- src/sass/main.scss
- src/sass/page/base.scss
- На все страницы добавлен компонент **ScrollButton** с соответствующими стилями для кнопки прокрутки.
- Внесены изменения в глобальный стиль `base.scss`:
- Стиль `height: 100%` блокировал событие `scroll`, поэтому он был заменён на:
```scss
min-height: 100%;
margin: 0;
```
Эти изменения не повлияли на остальной функционал, но теперь возможно отслеживать событие `scroll`.
- Кнопка теперь поддерживает передаваемый пропс `color` для задания кастомного цвета.
- Кнопка имеет плавную анимацию появления/скрытия и адаптивность для разных экранов.
- Улучшена логика отображения кнопки при прокрутке страницы.
- Примеры с другим цветом кнопки:
> [MS-1371] feat: add scroll-to-top button with custom styles

- src/sass/organism/new-page-header.scss
It seems like everything is normal now
> [MS-1420] changed media queries, as if everything is fine now

- src/atomic/page/vitamin.tsx
Добавлена адаптивность для мобильных устройств на страницу Витамин:
Теперь переход со строки на колонки в некоторых секциях происходит при ширине экрана менее 768px
> [MS-1360] fix: added adaptivity to the Vitamin page

- src/atomic/organism/navbar.tsx
Добавлена сортировка элементов в меню приложений по алфавиту на основе локализованных названий.
> [MS-1424] feat: sort app menu items alphabetically

- src/sass/organism/new-page-header.scss
Обновлены отступы в хедере в соответствии с макетом
> [MS-1429] fix: updated spacing in Header

- src/template/ar/waistline.ejs
- src/template/de/waistline.ejs
- src/template/en/waistline.ejs
- src/template/es/waistline.ejs
- src/template/fr/waistline.ejs
- src/template/hi/waistline.ejs
- src/template/ja/waistline.ejs
- src/template/pt/waistline.ejs
- src/template/ru/waistline.ejs
- src/template/uk/waistline.ejs
- src/template/zh/waistline.ejs
> [MS-1277] add LD-json to page Waisline

- src/template/ar/electrolyte.ejs
- src/template/de/electrolyte.ejs
- src/template/en/electrolyte.ejs
- src/template/es/electrolyte.ejs
- src/template/fr/electrolyte.ejs
- src/template/hi/electrolyte.ejs
- src/template/ja/electrolyte.ejs
- src/template/pt/electrolyte.ejs
- src/template/ru/electrolyte.ejs
- src/template/uk/electrolyte.ejs
- src/template/zh/electrolyte.ejs
add snippet on page Electrolyte
> [MS 1279] add snippet for page Electrolyte

- src/template/ar/emotion/independence.ejs
- src/template/de/emotion/independence.ejs
- src/template/en/emotion/independence.ejs
- src/template/es/emotion/independence.ejs
- src/template/fr/emotion/independence.ejs
- src/template/hi/emotion/independence.ejs
- src/template/ja/emotion/independence.ejs
- src/template/pt/emotion/independence.ejs
- src/template/ru/emotion/independence.ejs
- src/template/uk/emotion/independence.ejs
- src/template/zh/emotion/independence.ejs
Add snippet on page Emotion/Independence in all languages
> MS 1281 add snippet page emotion independence

- src/template/ar/emotion/energy.ejs
- src/template/de/emotion/energy.ejs
- src/template/en/emotion/energy.ejs
- src/template/es/emotion/energy.ejs
- src/template/fr/emotion/energy.ejs
- src/template/hi/emotion/energy.ejs
- src/template/ja/emotion/energy.ejs
- src/template/pt/emotion/energy.ejs
- src/template/ru/emotion/energy.ejs
- src/template/uk/emotion/energy.ejs
- src/template/zh/emotion/energy.ejs
Add all languages snippets on page Energy
> MS 1283 add snippet on page Energy

- src/atomic/page/main.tsx
удален текст "AXAX" и его строка
> deleted text on Energy block

- src/template/fr/emotion/anxiety.ejs
Я удалила запятую после последнего значения в объекте author. Теперь json валидный и все должно быть нормально
> remove comma after last value in object author

- src/atomic/atom/vacancy-status.tsx
- src/atomic/prototype/vacancy-details.tsx
- src/data/career-ar.json
- src/data/career-de.json
- src/data/career-en.json
- src/data/career-es.json
- src/data/career-fr.json
- src/data/career-hi.json
- src/data/career-ja.json
- src/data/career-pt.json
- src/data/career-ru.json
- src/data/career-uk.json
- src/data/career-zh.json
- src/sass/atom/vacancy-status.scss
- src/stories/atom/vacancy-status.stories.tsx
A new component has been created to display the current status of internships.
> [MS-1456] add internship status component

- src/atomic/organism/footer.tsx
- src/router.tsx
1. Add @/ to route file 
2. Add link Magnesium page to footer
> MS 1496 add link to page Magnesium to footer

- src/atomic/molecule/card-icon-title-text.tsx
- src/atomic/molecule/icon-title-text-elem.tsx
fix bug advantages section on pages Iron, Emotion
> MS 1511 fix bug advantages section

- src/template/ar/emotion/productivity.ejs
- src/template/de/emotion/productivity.ejs
- src/template/en/emotion/productivity.ejs
- src/template/es/emotion/productivity.ejs
- src/template/fr/emotion/productivity.ejs
- src/template/hi/emotion/productivity.ejs
- src/template/ja/emotion/productivity.ejs
- src/template/pt/emotion/productivity.ejs
- src/template/ru/emotion/productivity.ejs
- src/template/uk/emotion/productivity.ejs
- src/template/zh/emotion/productivity.ejs
сниппет для страницы Продуктивность сделан
> MS-1470: Snippet Productivity added

- src/atomic/page/bodysize.tsx
> MS 1503 remove code structure

- src/template/ar/about.ejs
- src/template/de/about.ejs
- src/template/en/about.ejs
- src/template/es/about.ejs
- src/template/fr/about.ejs
- src/template/hi/about.ejs
- src/template/ja/about.ejs
- src/template/pt/about.ejs
- src/template/ru/about.ejs
- src/template/uk/about.ejs
- src/template/zh/about.ejs
изменения в сниппете на About page: ProfilePage и interactionStatistic не поддерживаются вместе, поэтому меняю на WebPage, но если надо именно ProfilePage, то надо убрать interactionStatistic. с новыми изменениями на сайте https://search.google.com/test/rich-results показывает, что все без ошибок
> MS-1505: snippet error fix

- src/i18n/pt.json
заменен перевод на португальском
> MS-1515: fix Portuguese translation in homepage

- src/atomic/page/main.tsx
кнопки магния и железа на главной странице теперь выводят на свои страницы
> MS-1528: fixed output Magnesium and Iron buttons

- src/template/ar/emotion/biorhythms.ejs
- src/template/de/emotion/biorhythms.ejs
- src/template/en/emotion/biorhythms.ejs
- src/template/es/emotion/biorhythms.ejs
- src/template/fr/emotion/biorhythms.ejs
- src/template/hi/emotion/biorhythms.ejs
- src/template/ja/emotion/biorhythms.ejs
- src/template/pt/emotion/biorhythms.ejs
- src/template/ru/emotion/biorhythms.ejs
- src/template/uk/emotion/biorhythms.ejs
- src/template/zh/emotion/biorhythms.ejs
добавлен сниппет для страницы Биоритмы
> MS-1530: added snippet Biorhythms

- src/atomic/page/main.tsx
Add link to buttons: magnesium, calcium, iron, energy
> MS 1519 add link to buttons

- src/template/ar/team.ejs
- src/template/de/team.ejs
- src/template/en/team.ejs
- src/template/es/team.ejs
- src/template/fr/team.ejs
- src/template/hi/team.ejs
- src/template/ja/team.ejs
- src/template/pt/team.ejs
- src/template/ru/team.ejs
- src/template/uk/team.ejs
- src/template/zh/team.ejs
Сниппет для страницы команды добавлен
> MS-1537: Snippet Team added

- src/template/ar/careers.ejs
- src/template/de/careers.ejs
- src/template/en/careers.ejs
- src/template/es/careers.ejs
- src/template/fr/careers.ejs
- src/template/hi/careers.ejs
- src/template/ja/careers.ejs
- src/template/pt/careers.ejs
- src/template/ru/careers.ejs
- src/template/uk/careers.ejs
- src/template/zh/careers.ejs
- yarn.lock
сниппет для страницы Карьеры: 
JobPosting для вакансий, employmentType: "INTERN" для указания стажировки, jobLocationType: "TELECOMMUTE" для указания удаленной работы.
+ еще файл yarn.lock поменялся
> MS-1286: Snippet Career added

- package-lock.json
- src/atomic/molecule/card-title-text-image-custom.tsx
- src/atomic/page/bodysize.tsx
- src/sass/page/bodysize.scss
вывод карточек теперь нормальный: убрала ограничение на ширину, вместо этого авто настройка
> MS-1546: card bug fixed

- src/data/team/ar.json
- src/data/team/de.json
- src/data/team/en.json
- src/data/team/es.json
- src/data/team/fr.json
- src/data/team/hi.json
- src/data/team/ja.json
- src/data/team/pt.json
- src/data/team/ru.json
- src/data/team/uk.json
- src/data/team/zh.json
> Team Page Updated

- src/atomic/molecule/card-title-text-image-custom.tsx
- src/atomic/page/bodysize.tsx
карточки на странице Фигуры заменены, выглядят как на макете в фигме
> MS-1560: component replaced with CardTitleTextImageCustom
