- src/part/navbar.tsx
- src/sass/navigation.scss
- assigned .ms-s-offset class to navbar, to make sure it has the same width as all of the content through all breakpoints
- deleted excessive margins for lg screens
> [MS-260] Updated navbar offset

- webpack.com.js
- webpack.prd.js
- add bootstrap alignment classes to PurgeCSS plugin `safelist` for `CardImage` molecule:
- `align-items-start`, `align-items-center`, `align-items-end`
- `justify-content-start`, `justify-content-center`, `justify-content-end`
- add `clean` option to Webpack configuration to clean the `build` folder before each build
> [MS 1225] change PurgeCSS safelist for CardImage molecule

- src/atomic/molecule/card-title-text-image.tsx
- src/atomic/molecule/card-title-text.tsx
- src/sass/molecule/card-title-text-image.scss
- src/sass/molecule/card-title-text.scss
- correct font weight in `CardTitleTextImage` and `CardTitleText` molecules:
- from `os4` to `os3` for text. 
- `os4` sets font-weight to 400
- `os3` sets font-weight to 300
- `os3` is set for `<p>` on Vitamin page in `src\sass\page\base.scss`, class `ms-base-page`
- `os5` is set for `<h3>` on Vitamin page in `src\sass\page\base-new.scss`, class `ms-base-new`
- correct text width with padding in `CardTitleTextImage` molecule to be more consistent with the design
> [MS-1224] correct font weight in CardTitleTextImage and CardTitleText molecules

- src/atomic/molecule/card-title-text-image.tsx
- src/atomic/molecule/card-title-text.tsx
- src/atomic/page/vitamin.tsx
- src/sass/molecule/card-title-text-image.scss
- src/sass/molecule/card-title-text.scss
- add `titleColor` prop to `CardTitleTextImage` and `CardTitleText` molecules to set different colors for text and title
- change title color from `#151515` (new Vitamin page design) to `#212529` (current *title* color in other sections of Vitamin page)
- change text color from `#151515` (new Vitamin page design) to `#595959` (current *text* color in other sections of Vitamin page):
- color `#595959` gives a more consistent display of text boldness in Chrome and Firefox
- return font-weight 400 (font-family `os4`) for text in `CardTitleTextImage` and `CardTitleText` molecules
> [MS-1224] fix font-weight and default text color in CardTitleTextImage and CardTitleText molecules

- src/atomic/molecule/card-title-subtitle.tsx
- src/sass/molecule/card-title-subtitle.scss
- change the transparency of the subtitle color to 80% to match the design
- change the font-weight of the subtitle from 300 to 400
> [MS-1226] fix text transparency and weight in CardTitleSubtitle molecule

- src/atomic/molecule/card-vitamin.tsx
- src/atomic/page/vitamin.tsx
- change `CardVitamin` to get a hover color for the link and use the primary color as the base color for the link
- change color of vitamins on the Vitamin page:
- **fat-soluble vitamins**:
- vitamin and link color (primary color): `#E95813`
- link hover color: `#FF8F32`
- **water-soluble vitamins**:
- vitamin and link color (primary color): `#0F75DC`
- link hover color: `#399CFF`
- **minerals**:
- vitamin and link color (primary color): `#388205`
- link hover color: `#73C631`
> [MS-1227] correct CardVitamin for link hover color, change colors of vitamins on vitamin page

- src/stories/molecule/card-image.stories.tsx
Добавлена Ladle story для компонента CardImage (уровень - Молекула) с поддержкой динамической подстановки языка в пути к изображению.
> [MS-1318] Ladle: add CardImage story

- src/stories/molecule/card-title-text-button.stories.tsx
Добавлена Ladle story для компонента CardTitleTextButton, уровень - Молекула.
> [MS-1325] Ladle: add CardTitleTextButton story

- src/stories/molecule/card-title-text-image.stories.tsx
Добавлена Ladle story для компонента CardTitleTextImage , уровень - Молекула.
> [MS-1326] Ladle: add CardTitleTextImage story

- src/stories/molecule/card-title-text.stories.tsx
Добавлена Ladle story для компонента CardTitleText, уровень - Молекула.
> [MS-1327] Ladle: add CardTitleText story

- .ladle/decorators.tsx
- src/stories/atom/button-apple.stories.tsx
- src/stories/atom/icon-chevron-circle.stories.tsx
- src/stories/atom/icon-with-load.stories.tsx
- src/stories/atom/right-arrow-icon.stories.tsx
- src/stories/atom/star-icon.stories.tsx
Реализована обертка для иконок и кнопок. В качестве фона выбран светло-серый цвет, совпадающий с цветом правой панели Ladle. Он одновременно служит универсальной подложкой (на нем видны как светлые, так и темные элементы), и в то же время, благодаря совпадению с интерфейсом Ladle, не воспринимается как часть компонента.
> [Ms 1329] Ladle: add Icon Wrapper decorator

- src/stories/molecule/title-text-card.stories.tsx
Добавлена Ladle story для компонента TitleTextCard, уровень - Молекула.
> [MS-1341] Ladle: add TitleTextCard story

- src/stories/molecule/icon-title-text-elem.stories.tsx
Добавлена Ladle story для компонента IconTitleTextElem, уровень - Молекула.
> [MS-1332] Ladle: add IconTitleTextElem story

- src/atomic/molecule/text-link-arrow.tsx
- src/atomic/molecule/title-text-link-card.tsx
- src/atomic/page/careers.tsx
Это исправления к задаче 1249 https://martspec.atlassian.net/jira/software/c/projects/MS/boards/1?selectedIssue=MS-1249
Там есть связанные задачи 1365, 1366, 1367.
В этом коммите исправлена только 1365 -  в компоненты TextLinkArrow и Title-Text-Link-Card добавлены пропсы fontSize, fontFamily, чтобы ссылка больше соответствовала макету из фигмы
Также был баг с тем, что ссылки на страницу vacancy-details не работали, так как фоновое изображение находилось поверх них.
(Это произошло, когда мы делали компонент карты переиспользуемым и для Карьеры, и для Электролита (там карточки используются в секции минералов). И разные настройки z-index не подходили к обеим страницам.)
Сейчас этот баг 1299 уже закрыт https://martspec.atlassian.net/jira/software/c/projects/MS/issues/MS-1299?jql=project%20%3D% …
> Ms 1249 correcting defects

- src/atomic/prototype/vacancy-details.tsx
Bug https://martspec.atlassian.net/jira/software/c/projects/MS/boards/1?assignee=712020%3Ae0b156fe-c3ae-4471-bf53-7568ab7366f9&selectedIssue=MS-1349
the button was wrapped in a link so there was clickable space around it. this was partially fixed by adding d-inline-block w-auto classes to the link, but there was still a small clickable space at the bottom, under the button
removed the link and left only the button
> Ms 1349 correction link for responding to a vacancy

- src/atomic/organism/footer.tsx
- src/sass/organism/footer.scss
Исправлена ошибка, при которой ссылки в Footer были кликабельны за пределами текста. А также были изменены стили этих ссылок , чтобы Footer больше соответствовал макету (изменен цвет ссылок и добавлена плавность изменения цвета при наведении).
> [MS-1350] fix: fixed Footer links and changed some associated styles

- src/atomic/prototype/review.tsx
Исправлено изменение размера раздела отзывов с ПК версии на мобильную с ширины 992px на ширину 991px:
> [MS-1358] fix: fixed resize of the Review section

- src/atomic/atom/scroll-button.tsx
- src/sass/atom/scroll-button.scss
- **Исправлено отображение кнопки** на устройствах iOS и в браузере Mozilla Firefox. Устранены проблемы с версткой и стилями, из-за которых кнопка неправильно отображалась на этих платформах.
- **Решена ошибка с неактивной кнопкой** после резкого прерывания прокрутки. Теперь кнопка сразу становится активной после завершения прокрутки, даже при её внезапном прерывании.
> [MS-1388] fix: correct button display on iOS devices and Firefox, and resolve scroll interruption issue

- src/atomic/organism/call-to-action-new.tsx
- src/stories/organism/call-to-action-new.stories.tsx
Обновлен компонент CallToAction, пока сделан отдельный компонент call-to-action-new (и соответствующая сторис в ладли), чтобы его изолированно отработать перед внедрением в проект.
Изменения следующее:
1. Теперь кнопка передается отдельным пропсом как ReactNode.
2. Добавлен пропс textList (в некоторых кейсах с макетов может быть необходим). 
3. Пока textList сделан внутри верстки, но на будущее предлагаю сделать его отдельным компонентом (можно назвать BulletList, похожих компонентов я не нашел). Списки с буллет-поинтами повторяются довольно часто, сами буллет-поинты могут различаться по цвету. Цвет как раз было бы удобно передавать как пропс, плюс в рамках отдельного компонента удобнее настроить стили.
4. Добавлен пропс imgPosition (значения “left”/“right”, позволяет менять местами текст …
> [MS-1387] CallToAction component upgrade

- src/atomic/atom/button-chevron-right.tsx
Исправлена ошибка, из-за которой при нажатии на кнопку "Узнать больше" вокруг появлялась лишняя граница.
> [MS-1372] fix: delete "btn" class to remove extra border in active state

- src/sass/molecule/card-icon-title-text.scss
- src/sass/page/waist.scss
Исправлены отступы между блоками на странице Талия согласно макету в Figma  и убраны тени у залитых карточек.
> [MS-1432] fix: adjusted spacing and removed shadows from filled cards on Waist page

- src/i18n/pt.json
I added the missing TEXT1 entry to the translation file (src/i18n/pt.json). Previously, this entry was not present in the file, which resulted in the translation not appearing on the website. With this update, the translation should now be correctly displayed.
Let me know if you need any adjustments!
> MS-1441-portuguese-and-german-translation-issue-untranslated-card-zinc

- src/i18n/de.json
- Capitalized German nouns in description text as per language rules:
- `winzige Taille - gesundes Herz` → `Winzige Taille – Gesundes Herz`
[MS-1443] Capitalize nouns in description
[MS-1443]: https://martspec.atlassian.net/browse/MS-1443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [1443] Fix: capitalize nouns in German description

- src/sass/organism/new-page-header.scss
Fixed: Electrolyte: overlay element with image on screen width ≤991px for all languages except Russian
> [1389]fix: Electrolyte: overlay element with image on screen width ≤991

- src/atomic/page/mass.tsx
- src/atomic/page/waist.tsx
Добавлена адаптивность для мобильных устройств на страницы Талия и Вес:
Теперь переход со строки на колонки в некоторых секциях происходит при ширине экрана менее 768px
> [MS-1427] fix: made Waist and Weight pages responsive
